# Generated by Django 4.2 on 2025-03-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0012_delivery_is_payed_shop_latitude_shop_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='номер телефона'),
        ),
    ]
